apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    listKind: CronTabList

  # Этот YAML-файл определяет CustomResourceDefinition (CRD) для Kubernetes.
  # CRD позволяет создавать новые виды ресурсов, помимо тех, которые встроены в Kubernetes
  # (такие как Pods, Services, Deployments и т.д.).
  # В данном случае, CRD определяет новый тип ресурса под названием "CronTab".


  # CRD crontabs.stable.example.com позволяет  создавать, обновлять и управлять ресурсами типа CronTab
  # в нашем кластере Kubernetes.
  # Эти ресурсы могут быть использованы для определения и управления cron-задачами с помощью Kubernetes.